# Generated by Django 2.2.9 on 2020-01-29 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='HomeworkPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('instrument', models.TextField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('column', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homework', to='homework.HomeworkColumn')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='SingleChoiceQuestionPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('kind', models.TextField(default='SC')),
                ('stem', models.TextField()),
                ('choice_1', models.TextField()),
                ('choice_2', models.TextField()),
                ('choice_3', models.TextField()),
                ('choice_4', models.TextField()),
                ('answer', models.TextField()),
                ('homework', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='single_choice_question', to='homework.HomeworkPost')),
            ],
        ),
        migrations.CreateModel(
            name='ReadingComprehensionQuestionPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('kind', models.TextField(default='RC')),
                ('essay', models.TextField()),
                ('stem_1', models.TextField()),
                ('choice_1_1', models.TextField()),
                ('choice_1_2', models.TextField()),
                ('choice_1_3', models.TextField()),
                ('choice_1_4', models.TextField()),
                ('answer_1', models.TextField()),
                ('stem_2', models.TextField()),
                ('choice_2_1', models.TextField()),
                ('choice_2_2', models.TextField()),
                ('choice_2_3', models.TextField()),
                ('choice_2_4', models.TextField()),
                ('answer_2', models.TextField()),
                ('stem_3', models.TextField()),
                ('choice_3_1', models.TextField()),
                ('choice_3_2', models.TextField()),
                ('choice_3_3', models.TextField()),
                ('choice_3_4', models.TextField()),
                ('answer_3', models.TextField()),
                ('stem_4', models.TextField()),
                ('choice_4_1', models.TextField()),
                ('choice_4_2', models.TextField()),
                ('choice_4_3', models.TextField()),
                ('choice_4_4', models.TextField()),
                ('answer_4', models.TextField()),
                ('stem_5', models.TextField()),
                ('choice_5_1', models.TextField()),
                ('choice_5_2', models.TextField()),
                ('choice_5_3', models.TextField()),
                ('choice_5_4', models.TextField()),
                ('answer_5', models.TextField()),
                ('stem_6', models.TextField()),
                ('choice_6_1', models.TextField()),
                ('choice_6_2', models.TextField()),
                ('choice_6_3', models.TextField()),
                ('choice_6_4', models.TextField()),
                ('answer_6', models.TextField()),
                ('homework', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reading_comprehension_question', to='homework.HomeworkPost')),
            ],
        ),
    ]
