# Generated by Django 2.2.9 on 2020-01-29 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homeworkpost',
            old_name='body',
            new_name='instrument',
        ),
        migrations.CreateModel(
            name='SingleChoiceQuestionPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stem', models.TextField()),
                ('choice_1', models.TextField()),
                ('choice_2', models.TextField()),
                ('choice_3', models.TextField()),
                ('choice_4', models.TextField()),
                ('answer', models.CharField(max_length=4)),
                ('homework', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='single_choice_question', to='homework.HomeworkPost')),
            ],
        ),
    ]
