# Generated by Django 2.2.9 on 2020-01-29 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0002_auto_20200129_1530'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homeworkpost',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterField(
            model_name='singlechoicequestionpost',
            name='answer',
            field=models.TextField(),
        ),
    ]
